### ISSUE TITLE
No transform from [name1] to [name2]のエラーについて

### ISSUE THREAD

**Issue by wyd0817** [yuya-0411/Rviz_snake10#3]
コミット[151ad18de7](https://github.com/yuya-0411/Rviz_snake10/tree/151ad18de7a5da2fa7eb1ef503b31732186f1099)は検証したバージョンですかね。コミット[151ad18de7](https://github.com/yuya-0411/Rviz_snake10/tree/151ad18de7a5da2fa7eb1ef503b31732186f1099)をプルしましたが、コンパイルを通って、以下のno transform from [name1] to [name2]というエラーが出てきました。

![image](https://user-images.githubusercontent.com/25527726/142709927-a92cb1b7-b0f5-44fc-89a4-458a25a7b763.png)

**Comment by yuya-0411** [comment]
@wyd0817 
検証済みです．
一度，「rostopic info /joint_state_publisher_gui」と「rostopic info /joint_state_publisher」の結果を見せてください．
また，launchファイルのgui=trueのところをfalseにしてからも同じことを試してみてください．
お願いします．

**Comment by wyd0817** [comment]
「rostopic info /joint_state_publisher_gui」と「rostopic info /joint_state_publisher」の結果は以下のようになります。
![image](https://user-images.githubusercontent.com/25527726/142714058-190131b3-1b1a-4d6a-85cf-fee0724b156e.png)
rostopic listを実行して、以下の結果になります。
![image](https://user-images.githubusercontent.com/25527726/142714077-acf22b7c-bbd6-49b3-b114-54b2a490602c.png)
rostopic echo /joint_statesを実行したら、以下のようになります。
![image](https://user-images.githubusercontent.com/25527726/142714102-e909355a-9db4-45eb-8f77-065926835a6b.png)

また、launchファイルのgui=trueのところをfalseにしてからも同じ結果でした。

お願いします。

**Comment by yuya-0411** [comment]
@wyd0817 
ごめんなさい．間違えてました．
「rostopic info /joint_states」としてください．
お願いします．

**Comment by wyd0817** [comment]
いいえ。実行したら、以下の赤枠のようになりました。
![image](https://user-images.githubusercontent.com/25527726/142729585-046c72b3-bbcd-4b7d-bb49-72fc8bdd3057.png)

**Comment by yuya-0411** [comment]
@wyd0817 
分かりました．
原因は，Fixed Frameがbase_linkになっているからです．その部分ではworldを選択するとうまくいくと思います．
それを変更後，Rvizのcofigを上書き保存すれば，次回以降は特に問題なく，動くと思います．

**Comment by wyd0817** [comment]
それで解決できました。ありがとうございます。
